postman.default.dbName=anchorRubicon

#spring.data.mongodb.database=anchorRubicon
spring.data.mongodb.uri=mongodb://localhost:27017/rubiconwater
spring.main.allow-bean-definition-overriding=true
server.port=8100

spring.data.mongodb.auto-index-creation = true
